@echo off
msg * compromised system
msg * compromised system
msg * compromised system
msg * compromised system
msg * compromised system
msg * compromised system
msg * compromised system
shutdown -r -t 30 -c 'msg * compromised system'
msg * compromised system
msg * compromised system
msg * compromised system
msg * compromised system
msg * compromised system
msg * compromised system
msg * compromised system
msg * compromised system
msg * compromised system
msg * compromised system
msg * compromised system
msg * compromised system
msg * compromised system
msg * compromised system
msg * compromised system
msg * compromised system
msg * compromised system
msg * compromised system
msg * compromised system
msg * compromised system
msg * compromised system